# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
          - name: POSTGRES_USER
            value: "kubedevnews"
          - name: POSTGRES_DB
            value: "kubedevnews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: joaocmreis/kube-news:latest
        env:
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_USERNAME
          value: "kubedevnews"
        - name: DB_DATABASE
          value: "kubedevnews"
        - name: DB_HOST
          value: "postgre"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  # NodePort para k3d, LoadBalancer para nuvem
  # type: NodePort
  type: LoadBalancer

